# SITE CONFIGURATION
title: PEDP
author: Ryan Amaral
description: > # Meta description of Homepage
  Coaching
baseurl: ""
url: "https://www.pedp.pt"

# SEO PLUGIN
social:
  name:
  links:

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Início', link: '/'}
  - {name: 'Sobre', link: '/sobre'}
  - {name: 'Contacto', link: '/contacto'}

tagline: >
  Coaching

hero_img: posts/pedp-compressed.png # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: your-email@domain.com # email for form submission

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

sass:
    sass_dir: _sass

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
